addpath('utils')
clear all; close all; clc;

preprocess_combine_experiments()
% preprocess_create_master_table()
% estimate_polynomial_mvav()
% table1()
% figure2()
% figure3A()
% figure3B()
% figure4()
% figureS1()
% figureS2()
% figureS3()
% linear_mixed_models()