name: Python Data Reanalysis

on:
  push:
    branches:
      - '**'  # Runs on all branches

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4  # Fetch repo contents

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Replace with your required Python version

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Track Existing Files Before Running Python
      run: |
        mkdir -p output
        find . -type f -name "*.mat" -o -name "*.csv" > before_run.txt

    - name: Run Python Analysis
      run: |
        python main_function.py  # Replace with your actual Python script name

    - name: Identify Newly Created Files
      run: |
        find . -type f -name "*.mat" -o -name "*.csv" > after_run.txt
        comm -13 before_run.txt after_run.txt > new_files.txt
        mkdir -p output
        cat new_files.txt | xargs -I {} mv "{}" output/ || true
