name: Python Data Reanalysis

on:
  push:
    branches:
      - '**'  # Runs on all branches

jobs:
  run-python:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # <--- Grant write permission to the contents
      
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4  # Fetch repo contents
      with:
        persist-credentials: true
        
    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.5'  # Replace with your required Python version

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python Analysis
      run: |
        python main_function.py  

    - name: Commit Generated Files
      uses: EndBug/add-and-commit@v9
      with:
        add: "/home/runner/work/try/try/data/datasets/*.csv /home/runner/work/try/try/data/studies/*.csv"  
        message: "Update generated CSV files"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    
