name: Python Data Reanalysis

on:
  push:
    branches:
      - '**'  # Runs on all branches

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4  # Fetch repo contents

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Replace with your required Python version

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python Analysis
      run: |
        python main_function.py  # Replace with your actual Python script name

    - name: List Files After Python Run
      run: |
        echo "Listing all files in the repository:"
        ls -laR .

    # Commit new CSV and MAT files if any are generated
    - name: Commit Generated Files
      uses: EndBug/add-and-commit@v9
      with:
        author_name: GitHub Action
        author_email: action@github.com
        message: "Update generated CSV/MAT files"
        add: "output/*.csv"  # Adjust this path as needed
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
